//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopCalculator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopCalculator.LayoutResource", typeof(LayoutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMr.
        /// </summary>
        public static string btnMrName {
            get {
                return ResourceManager.GetString("btnMrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE.
        /// </summary>
        public static string CEBtnTag {
            get {
                return ResourceManager.GetString("CEBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnCe.
        /// </summary>
        public static string CEName {
            get {
                return ResourceManager.GetString("CEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE.
        /// </summary>
        public static string CEText {
            get {
                return ResourceManager.GetString("CEText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Current Input.
        /// </summary>
        public static string CeToolTip {
            get {
                return ResourceManager.GetString("CeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnClear.
        /// </summary>
        public static string ClearBtnName {
            get {
                return ResourceManager.GetString("ClearBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string ClearBtnTag {
            get {
                return ResourceManager.GetString("ClearBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string ClearbtnText {
            get {
                return ResourceManager.GetString("ClearbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearToolTip {
            get {
                return ResourceManager.GetString("ClearToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnCos.
        /// </summary>
        public static string CosBtnName {
            get {
                return ResourceManager.GetString("CosBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cos.
        /// </summary>
        public static string CosBtnTag {
            get {
                return ResourceManager.GetString("CosBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cos.
        /// </summary>
        public static string CosBtnText {
            get {
                return ResourceManager.GetString("CosBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnCos.
        /// </summary>
        public static string CosBtnToolTip {
            get {
                return ResourceManager.GetString("CosBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnDivOp.
        /// </summary>
        public static string DivBtnName {
            get {
                return ResourceManager.GetString("DivBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string DivBtnTag {
            get {
                return ResourceManager.GetString("DivBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string DivBtnText {
            get {
                return ResourceManager.GetString("DivBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Division.
        /// </summary>
        public static string DivBtnToolTip {
            get {
                return ResourceManager.GetString("DivBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnDot.
        /// </summary>
        public static string DotBtnName {
            get {
                return ResourceManager.GetString("DotBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string DotBtnTag {
            get {
                return ResourceManager.GetString("DotBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string DotBtnText {
            get {
                return ResourceManager.GetString("DotBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string DotBtnToolTip {
            get {
                return ResourceManager.GetString("DotBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnEight.
        /// </summary>
        public static string EightBtnName {
            get {
                return ResourceManager.GetString("EightBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string EightBtnTag {
            get {
                return ResourceManager.GetString("EightBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string EightBtnText {
            get {
                return ResourceManager.GetString("EightBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string EightBtnToolTip {
            get {
                return ResourceManager.GetString("EightBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnEqual.
        /// </summary>
        public static string EqualBtnName {
            get {
                return ResourceManager.GetString("EqualBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string EqualBtnTag {
            get {
                return ResourceManager.GetString("EqualBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string EqualBtnText {
            get {
                return ResourceManager.GetString("EqualBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate.
        /// </summary>
        public static string EqualBtnToolTip {
            get {
                return ResourceManager.GetString("EqualBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labelEquation.
        /// </summary>
        public static string EquationLabeName {
            get {
                return ResourceManager.GetString("EquationLabeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnEscape.
        /// </summary>
        public static string EScName {
            get {
                return ResourceManager.GetString("EScName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ←.
        /// </summary>
        public static string EscText {
            get {
                return ResourceManager.GetString("EscText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete one digit.
        /// </summary>
        public static string EscToolTip {
            get {
                return ResourceManager.GetString("EscToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnExpConst.
        /// </summary>
        public static string ExpBtnName {
            get {
                return ResourceManager.GetString("ExpBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        public static string ExpBtnTag {
            get {
                return ResourceManager.GetString("ExpBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        public static string ExpBtnText {
            get {
                return ResourceManager.GetString("ExpBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives The Value Of e.
        /// </summary>
        public static string ExpBtnToolTip {
            get {
                return ResourceManager.GetString("ExpBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnFive.
        /// </summary>
        public static string FiveBtnName {
            get {
                return ResourceManager.GetString("FiveBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string FiveBtnTag {
            get {
                return ResourceManager.GetString("FiveBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string FiveBtnText {
            get {
                return ResourceManager.GetString("FiveBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string FiveToolTip {
            get {
                return ResourceManager.GetString("FiveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Sans Serif.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnFour.
        /// </summary>
        public static string FourBtnName {
            get {
                return ResourceManager.GetString("FourBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string FourBtnTag {
            get {
                return ResourceManager.GetString("FourBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string FourBtnText {
            get {
                return ResourceManager.GetString("FourBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string FourToolTip {
            get {
                return ResourceManager.GetString("FourToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        public static string GeorgiaFont {
            get {
                return ResourceManager.GetString("GeorgiaFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpLayoutName {
            get {
                return ResourceManager.GetString("HelpLayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inputTxtbox.
        /// </summary>
        public static string InputTextBox {
            get {
                return ResourceManager.GetString("InputTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inputTxtbox.
        /// </summary>
        public static string InputTextBoxName {
            get {
                return ResourceManager.GetString("InputTextBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Desktop Calculator.
        /// </summary>
        public static string LableHelpTitle {
            get {
                return ResourceManager.GetString("LableHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnLog.
        /// </summary>
        public static string LogBtnName {
            get {
                return ResourceManager.GetString("LogBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogBtnTag {
            get {
                return ResourceManager.GetString("LogBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogBtnText {
            get {
                return ResourceManager.GetString("LogBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogBtnToolTip {
            get {
                return ResourceManager.GetString("LogBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Martz90_Circle_Calculator {
            get {
                object obj = ResourceManager.GetObject("Martz90_Circle_Calculator", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMc.
        /// </summary>
        public static string McBtnName {
            get {
                return ResourceManager.GetString("McBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        public static string McBtnTag {
            get {
                return ResourceManager.GetString("McBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        public static string McBtnText {
            get {
                return ResourceManager.GetString("McBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the stored Value.
        /// </summary>
        public static string McBtnToolTip {
            get {
                return ResourceManager.GetString("McBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Decrement.
        /// </summary>
        public static string MDecToolTip {
            get {
                return ResourceManager.GetString("MDecToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMInc.
        /// </summary>
        public static string MIncName {
            get {
                return ResourceManager.GetString("MIncName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        public static string MIncTag {
            get {
                return ResourceManager.GetString("MIncTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMinusOp.
        /// </summary>
        public static string MinusBtnName {
            get {
                return ResourceManager.GetString("MinusBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string MinusBtnTag {
            get {
                return ResourceManager.GetString("MinusBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string MinusBtnText {
            get {
                return ResourceManager.GetString("MinusBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to performSubTraction.
        /// </summary>
        public static string MinusBtnToolTip {
            get {
                return ResourceManager.GetString("MinusBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMMinus.
        /// </summary>
        public static string MminusName {
            get {
                return ResourceManager.GetString("MminusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-.
        /// </summary>
        public static string MminusTag {
            get {
                return ResourceManager.GetString("MminusTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrement the Ms Value By One.
        /// </summary>
        public static string MMinusToolTip {
            get {
                return ResourceManager.GetString("MMinusToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMod.
        /// </summary>
        public static string ModBtnName {
            get {
                return ResourceManager.GetString("ModBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string ModBtnTag {
            get {
                return ResourceManager.GetString("ModBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string ModBtnText {
            get {
                return ResourceManager.GetString("ModBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string ModToolTip {
            get {
                return ResourceManager.GetString("ModToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M+.
        /// </summary>
        public static string MPlusbtnText {
            get {
                return ResourceManager.GetString("MPlusbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMPlus.
        /// </summary>
        public static string MPlusName {
            get {
                return ResourceManager.GetString("MPlusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M+.
        /// </summary>
        public static string MPlusTag {
            get {
                return ResourceManager.GetString("MPlusTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment the Ms Value By One.
        /// </summary>
        public static string MPlusToolTip {
            get {
                return ResourceManager.GetString("MPlusToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMr.
        /// </summary>
        public static string MrBtnName {
            get {
                return ResourceManager.GetString("MrBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR.
        /// </summary>
        public static string MrBtnTag {
            get {
                return ResourceManager.GetString("MrBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR.
        /// </summary>
        public static string MrBtnText {
            get {
                return ResourceManager.GetString("MrBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Restorred.
        /// </summary>
        public static string MrToolTip {
            get {
                return ResourceManager.GetString("MrToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMs.
        /// </summary>
        public static string MsBtnName {
            get {
                return ResourceManager.GetString("MsBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        public static string MsBtnTag {
            get {
                return ResourceManager.GetString("MsBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        public static string MsBtnText {
            get {
                return ResourceManager.GetString("MsBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store the the current value.
        /// </summary>
        public static string MsBtnToolTip {
            get {
                return ResourceManager.GetString("MsBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMulOp.
        /// </summary>
        public static string MulBtnName {
            get {
                return ResourceManager.GetString("MulBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string MulBtnTag {
            get {
                return ResourceManager.GetString("MulBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string MulBtnText {
            get {
                return ResourceManager.GetString("MulBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Multiply.
        /// </summary>
        public static string MulBtnTooltip {
            get {
                return ResourceManager.GetString("MulBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCalc.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btNine.
        /// </summary>
        public static string NineBtnName {
            get {
                return ResourceManager.GetString("NineBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string NineBtnTag {
            get {
                return ResourceManager.GetString("NineBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string NineBtnText {
            get {
                return ResourceManager.GetString("NineBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string NineBtnToolTip {
            get {
                return ResourceManager.GetString("NineBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnOne.
        /// </summary>
        public static string OneBtnName {
            get {
                return ResourceManager.GetString("OneBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string OneBtnTag {
            get {
                return ResourceManager.GetString("OneBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string OneBtnText {
            get {
                return ResourceManager.GetString("OneBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnOneDivXOp.
        /// </summary>
        public static string OneDivXName {
            get {
                return ResourceManager.GetString("OneDivXName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/x.
        /// </summary>
        public static string OneDivXTag {
            get {
                return ResourceManager.GetString("OneDivXTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/x.
        /// </summary>
        public static string OneDivXText {
            get {
                return ResourceManager.GetString("OneDivXText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Division.
        /// </summary>
        public static string OneDivXToolTip {
            get {
                return ResourceManager.GetString("OneDivXToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string OneToolTip {
            get {
                return ResourceManager.GetString("OneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnPi.
        /// </summary>
        public static string PiBtnName {
            get {
                return ResourceManager.GetString("PiBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∏.
        /// </summary>
        public static string PiBtnTag {
            get {
                return ResourceManager.GetString("PiBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∏.
        /// </summary>
        public static string PiBtnText {
            get {
                return ResourceManager.GetString("PiBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives the value of Pi.
        /// </summary>
        public static string PiBtnToolTip {
            get {
                return ResourceManager.GetString("PiBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnPlusOp.
        /// </summary>
        public static string PlusBtnName {
            get {
                return ResourceManager.GetString("PlusBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string PlusBtnTag {
            get {
                return ResourceManager.GetString("PlusBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string PlusBtnText {
            get {
                return ResourceManager.GetString("PlusBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Addition.
        /// </summary>
        public static string PlusBtnToolTip {
            get {
                return ResourceManager.GetString("PlusBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnPlusMinus.
        /// </summary>
        public static string PlusMinusBtnName {
            get {
                return ResourceManager.GetString("PlusMinusBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ±.
        /// </summary>
        public static string PlusMinusBtnTag {
            get {
                return ResourceManager.GetString("PlusMinusBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ±.
        /// </summary>
        public static string PlusMinusBtnText {
            get {
                return ResourceManager.GetString("PlusMinusBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Sign.
        /// </summary>
        public static string PlusMinusBtnToolTip {
            get {
                return ResourceManager.GetString("PlusMinusBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnRoot.
        /// </summary>
        public static string RootBtnName {
            get {
                return ResourceManager.GetString("RootBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string RootBtnTag {
            get {
                return ResourceManager.GetString("RootBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to √.
        /// </summary>
        public static string RootBtnText {
            get {
                return ResourceManager.GetString("RootBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Root.
        /// </summary>
        public static string rootTooltip {
            get {
                return ResourceManager.GetString("rootTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Scientific.
        /// </summary>
        public static string Scientific {
            get {
                return ResourceManager.GetString("Scientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnSeven.
        /// </summary>
        public static string SevenBtnName {
            get {
                return ResourceManager.GetString("SevenBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string SevenBtnTag {
            get {
                return ResourceManager.GetString("SevenBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string SevenBtnText {
            get {
                return ResourceManager.GetString("SevenBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string SevenBtnToolTip {
            get {
                return ResourceManager.GetString("SevenBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnSine.
        /// </summary>
        public static string SineBtnName {
            get {
                return ResourceManager.GetString("SineBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine.
        /// </summary>
        public static string SineBtnTag {
            get {
                return ResourceManager.GetString("SineBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine.
        /// </summary>
        public static string SineBtnText {
            get {
                return ResourceManager.GetString("SineBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine Value.
        /// </summary>
        public static string SineBtnToolTip {
            get {
                return ResourceManager.GetString("SineBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnSix.
        /// </summary>
        public static string SixBtnName {
            get {
                return ResourceManager.GetString("SixBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string SixBtnTag {
            get {
                return ResourceManager.GetString("SixBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string SixBtnText {
            get {
                return ResourceManager.GetString("SixBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string SixToolTip {
            get {
                return ResourceManager.GetString("SixToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tableLayoutHelp.
        /// </summary>
        public static string TableLayoutName {
            get {
                return ResourceManager.GetString("TableLayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnTan.
        /// </summary>
        public static string TanBtnName {
            get {
                return ResourceManager.GetString("TanBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        public static string TanBtnTag {
            get {
                return ResourceManager.GetString("TanBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        public static string TanBtnText {
            get {
                return ResourceManager.GetString("TanBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tan(x) Value.
        /// </summary>
        public static string TanBtnToolTip {
            get {
                return ResourceManager.GetString("TanBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnThree.
        /// </summary>
        public static string ThreeBtnName {
            get {
                return ResourceManager.GetString("ThreeBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string ThreeBtnTag {
            get {
                return ResourceManager.GetString("ThreeBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string ThreeBtnText {
            get {
                return ResourceManager.GetString("ThreeBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three.
        /// </summary>
        public static string ThreeToolTip {
            get {
                return ResourceManager.GetString("ThreeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnTwo.
        /// </summary>
        public static string TwoBtnName {
            get {
                return ResourceManager.GetString("TwoBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string TwoBtnTag {
            get {
                return ResourceManager.GetString("TwoBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string TwoBtnText {
            get {
                return ResourceManager.GetString("TwoBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two.
        /// </summary>
        public static string TwoToolTip {
            get {
                return ResourceManager.GetString("TwoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string WinCalcText {
            get {
                return ResourceManager.GetString("WinCalcText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnXFact.
        /// </summary>
        public static string XFactBtnName {
            get {
                return ResourceManager.GetString("XFactBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x!.
        /// </summary>
        public static string XFactBtnTag {
            get {
                return ResourceManager.GetString("XFactBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X!.
        /// </summary>
        public static string XFactBtnText {
            get {
                return ResourceManager.GetString("XFactBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to factorial of x.
        /// </summary>
        public static string XFactBtnTooTip {
            get {
                return ResourceManager.GetString("XFactBtnTooTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnXPowTwo.
        /// </summary>
        public static string XPowTwoBtnName {
            get {
                return ResourceManager.GetString("XPowTwoBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x^2.
        /// </summary>
        public static string XPowTwoBtnTag {
            get {
                return ResourceManager.GetString("XPowTwoBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x^2.
        /// </summary>
        public static string XPowTwoBtnText {
            get {
                return ResourceManager.GetString("XPowTwoBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate x^2.
        /// </summary>
        public static string XPowTwoBtnToolTip {
            get {
                return ResourceManager.GetString("XPowTwoBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnXPowY.
        /// </summary>
        public static string XPowYBtnName {
            get {
                return ResourceManager.GetString("XPowYBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        public static string XPowYBtnTag {
            get {
                return ResourceManager.GetString("XPowYBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        public static string XPowYBtnText {
            get {
                return ResourceManager.GetString("XPowYBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evaluate x^y.
        /// </summary>
        public static string XPowYBtnToolTip {
            get {
                return ResourceManager.GetString("XPowYBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnXQube.
        /// </summary>
        public static string XQubeBtnName {
            get {
                return ResourceManager.GetString("XQubeBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x^3.
        /// </summary>
        public static string XQubeBtnTag {
            get {
                return ResourceManager.GetString("XQubeBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x^3.
        /// </summary>
        public static string XQubeBtnText {
            get {
                return ResourceManager.GetString("XQubeBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evaluate x^3.
        /// </summary>
        public static string XQubeBtnToolTip {
            get {
                return ResourceManager.GetString("XQubeBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnZero.
        /// </summary>
        public static string ZeroBtnName {
            get {
                return ResourceManager.GetString("ZeroBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string ZeroBtnTag {
            get {
                return ResourceManager.GetString("ZeroBtnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string ZeroBtnText {
            get {
                return ResourceManager.GetString("ZeroBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string ZeroBtnToolTip {
            get {
                return ResourceManager.GetString("ZeroBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero .
        /// </summary>
        public static string Zerotoolitp {
            get {
                return ResourceManager.GetString("Zerotoolitp", resourceCulture);
            }
        }
    }
}
